### ISSUE TITLE
question about `From`

### ISSUE THREAD

**Issue by HaveF** [jadsonlourenco/docker-mongo-rocks#1]
Thanks for your container! Do love it.
Btw, I want to ask a question if you have free time to answer....
I see [the docker file](https://github.com/jadsonlourenco/docker-mongo-rocks/blob/master/Dockerfile#L1)
`FROM ubuntu:16.04`

Does `percona-server-mongodb` depends a lot with ubuntu? Or just for convenient to use?

I suppose  [alpine](https://hub.docker.com/_/alpine/) is the smallest base image.

Just a quick question about this. Thanks for your work again!

**Comment by jadsonlourenco** [comment]
@HaveF No, Percona server for MongoDB can run or compile on any Linux distro, but in my experience using Ubuntu is more easy, a lot of the apps, like this one, has a repository for Ubuntu/Debian, in this case has precompiled binaries, save time. 

Alpine is great, but somethings don't works pretty well or don't have the Alpine bin ready to use, so, need install dependencies and compile to run, when build the Docker image. 
In this image the time to build the Docker Image is based on the internet speed - on datacenter has a good connection - and the image size is big, but not because of Ubuntu, only the MongoDB bin has like 300mb.

So, my experience is that: if you get from Alpine repo the app that you need and it works well, go ahead with Alpine, otherwise go with Ubuntu because will have all ready to use. The image size and build time is important if you need build a new image many times per month, if not this is not a problem, I will need more time to make my app compatible with Alpine. This is my opinion.

Thank you!

**Comment by HaveF** [comment]
> only the MongoDB bin has like 300mb.

Wow, Amazing.

Thanks for sharing your thoughts about it! I do believe it is a nice tradeoff :+1:
